name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # Step 2: Configure Git identity
      - name: Configure Git identity
        run: |
          git config --global user.email "raghu6a6@gmail.com"
          git config --global user.name "raghuramg666"

      # Step 3: Pull latest changes with conflict resolution
      - name: Pull latest changes
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config pull.rebase false
          git pull --allow-unrelated-histories https://raghu6a6:$HF_TOKEN@huggingface.co/spaces/raghu6a6/Search_Engine_LLM main || true
          
      # Step 4: Resolve conflicts (if any)
      - name: Resolve merge conflicts
        if: ${{ failure() }}
        run: |
          git checkout --ours README.md  # Keep local changes
          git add README.md
          git commit -m "Resolved conflicts in README.md"

      # Step 5: Push updates to Hugging Face hub
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://raghu6a6:$HF_TOKEN@huggingface.co/spaces/raghu6a6/Search_Engine_LLM main
